name: CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Welcome Message
        run: echo "GitHub Actions CI Pipeline Executed Successfully!"

      - name: Display Current Directory
        run: pwd

      - name: List Project Files
        run: ls -la

      - name: Display Completion Message
        run: echo "Pipeline Completed Successfully."
